[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hushdesk"
version = "0.1.0"
description = "HushDesk v0"
authors = [{name = "HushDesk"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pdfplumber==0.11.4",
  "pymupdf==1.24.9",
  "ttkbootstrap==1.10.1",
  "pillow==10.4.0",
  "pandas==2.2.3",
  "tzdata==2025.1",
  "typing-extensions==4.12.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
