name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy bandit pytest
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy hushdesk
      - name: Bandit
        run: bandit -r hushdesk
      - name: Pytest
        run: pytest
