name: ci / syntax-and-sims

on:
  pull_request:
  push:
    branches: [ release/win-startup-alpha, main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: syntax-and-sims-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-and-sims:
    name: syntax-and-sims
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project (editable) + runtime deps
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          python -m pip install -U pip wheel
          python -m pip install -e .[dev]
          python -m pip install tzdata pymupdf

      - name: Syntax (compile tree)
        shell: pwsh
        run: python -m compileall -q src

      - name: Preflight import & CLI
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          python -c "import sys, hushdesk; print('PYTHON:', sys.version); print('HUSHDESK:', hushdesk.__file__)"
          python -m hushdesk.cli --help
          python -m hushdesk.cli self-check --help

      - name: Run tests if present
        shell: pwsh
        run: |
          if (Test-Path .\\tests) {
            python -m pip install pytest
            pytest -q
          } else {
            Write-Host "No tests/ directory; skipping pytest."
          }

